# Usa a imagem oficial do n8n pronta para execução
FROM n8nio/n8n:latest

# Define o diretório de trabalho
WORKDIR /home/node

# Define o fuso horário
ENV GENERIC_TIMEZONE=America/Sao_Paulo

# Corrige permissões automaticamente (aviso que apareceu no seu log)
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

# Expõe a porta padrão do n8n
EXPOSE 5678

# Inicia o servidor n8n
CMD ["n8n", "start"]